### PR TITLE
chore: reduce memory layout

### PR DESCRIPTION
**Pull request by yjhmelody**
Can it reduce 4 bytes of memory overhead? I'm not sure

### CODE REVIEW

**Comment by MaxGraey** [comment]
[Variant takes 32 bytes in memory](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmltcG9ydCB7IE9CSkVDVF9PVkVSSEVBRCB9IGZyb20gInJ0L2NvbW1vbiI7CgpjbGFzcyBWYXJpYW50IHsKICBkaXNjcmltaW5hdG9yOiBpMzIgPSAwOwogIHN0b3JhZ2U6IHU2NCA9IDA7Cn0KCmV4cG9ydCBmdW5jdGlvbiB0b3RhbFNpemVPZlZhcmlhbnQoKTogdXNpemUgewogIHJldHVybiBvZmZzZXRvZjxWYXJpYW50PigpICsgT0JKRUNUX09WRVJIRUFEOwp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==) which is ok. Not sure how you could reduce this without loosing 16 byte alignment

**Comment by yjhmelody** [comment]
> [Variant takes 32 bytes in memory](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmltcG9ydCB7IE9CSkVDVF9PVkVSSEVBRCB9IGZyb20gInJ0L2NvbW1vbiI7CgpjbGFzcyBWYXJpYW50IHsKICBkaXNjcmltaW5hdG9yOiBpMzIgPSAwOwogIHN0b3JhZ2U6IHU2NCA9IDA7Cn0KCmV4cG9ydCBmdW5jdGlvbiB0b3RhbFNpemVPZlZhcmlhbnQoKTogdXNpemUgewogIHJldHVybiBvZmZzZXRvZjxWYXJpYW50PigpICsgT0JKRUNUX09WRVJIRUFEOwp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==) which is ok. Not sure how you could reduce this without loosing 16 byte alignment

https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmltcG9ydCB7IE9CSkVDVF9PVkVSSEVBRCB9IGZyb20gInJ0L2NvbW1vbiI7CgpjbGFzcyBWYXJpYW50IHsKICBkaXNjcmltaW5hdG9yOiBpMzIgPSAwOwogIHN0b3JhZ2U6IHUzMj0gMDsKICBzOiB1MzIKfQoKZXhwb3J0IGZ1bmN0aW9uIHRvdGFsU2l6ZU9mVmFyaWFudCgpOiB1c2l6ZSB7CiAgcmV0dXJuIG9mZnNldG9mPFZhcmlhbnQ+KCkgKyBPQkpFQ1RfT1ZFUkhFQUQ7Cn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogICAgICBvdXRwdXQudmFsdWUgKz0gYGZpYigke2l9KSA9ICR7ZXhwb3J0cy5maWIoaSl9XG5gCiAgICB9CiAgfSkKPC9zY3JpcHQ+

storage is u64，split it to two u32 can save 4bytes

**Comment by MaxGraey** [comment]
> storage is u64，split it to two u32 can save 4bytes

yes, but as I mentioned we loose 16-byte alignment which affect to access performance and allocator internally uses minimal size in 16 bytes anyway so in fact it will still be allocated 32 bytes

**Comment by yjhmelody** [comment]
Why need 16bytes align？

**Comment by MaxGraey** [comment]
> Why need 16bytes align？

1) it's required [for v128](https://github.com/AssemblyScript/assemblyscript/blob/main/std/assembly/rt/common.ts#L4)
2) it's optimal minimal block for gc + mem header info

**Pull request closed without merging**
